server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://158.180.75.120:3306/PMS_PROJECT
    driver-class-name: org.mariadb.jdbc.Driver
    username: ADMINUSER
    password: ADMINUSER
  messages:
    basename: messages
    encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true  # sql ??? ?????.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql ??? ????? ?????.

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace  # query? ?? ?? ?? ????? ??? ? ?? ?????. TRACE Log? ?? ?????.


file:
  dir: 'C:\servFile'


jwt:
  expiration_time: 86400000 #1일
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHaasdfasfsefawefawefawefawefawefawefawefawe432432fe2362623342
